import { randomUUID } from "node:crypto";
import type { Event } from "./models/event.js";
import type { EventRepository } from "./repository/index.js";
import { createLogger } from "./logging/logger.js";
import type { Logger } from "pino";

const generatedVenueId = "550e8400-e29b-41d4-a716-446655440000";

export interface EventGenerator {
  start(): void;
  stop(): void;
}

export function createEventGenerator(
  repository: EventRepository,
  intervalMs = 10_000,
  now: () => Date = () => new Date(),
  logger: Logger = createLogger({ service: "app-events" }),
): EventGenerator {
  let interval: NodeJS.Timeout | undefined;

  const generateEvent = (): Event => {
    const startsAt = now();
    const endsAt = new Date(startsAt.getTime() + 2 * 60 * 60 * 1000);
    const event: Event = {
      id: randomUUID(),
      name: `Generated event ${startsAt.toISOString()}`,
      description: "Event generated by the app-events startup process",
      venueId: generatedVenueId,
      startsAt: startsAt.toISOString(),
      endsAt: endsAt.toISOString(),
      status: "confirmed",
    };

    const savedEvent = repository.save(event);
    logger.info({ eventId: savedEvent.id, operation: "generateEvent" }, "event generated");
    return savedEvent;
  };

  return {
    start: () => {
      if (interval) {
        return;
      }

      generateEvent();
      interval = setInterval(generateEvent, intervalMs);
    },
    stop: () => {
      if (!interval) {
        return;
      }

      clearInterval(interval);
      interval = undefined;
    },
  };
}
