import { randomUUID } from "node:crypto";
import type { Event } from "./models/event.js";
import type { Artist } from "./models/artist.js";
import type { Venue } from "./models/venue.js";
import type { EventRepository } from "./repository/index.js";
import { createLogger } from "./logging/logger.js";
import type { Logger } from "pino";

export interface EventGenerator {
  start(): void;
  stop(): void;
}

export function createEventGenerator(
  repository: EventRepository,
  artists: readonly Artist[],
  venues: readonly Venue[],
  intervalMs = 10_000,
  now: () => Date = () => new Date(),
  logger: Logger = createLogger({ service: "app-events" }),
): EventGenerator {
  let interval: NodeJS.Timeout | undefined;

  if (artists.length === 0 || venues.length === 0) {
    throw new Error("Event generation requires at least one artist and venue");
  }

  const generateEvent = (): Event => {
    const startsAt = now();
    const endsAt = new Date(startsAt.getTime() + 2 * 60 * 60 * 1000);
    const artist = artists[Math.floor(Math.random() * artists.length)];
    const venue = venues[Math.floor(Math.random() * venues.length)];
    const event: Event = {
      id: randomUUID(),
      name: `${artist.name} live at ${venue.name}`,
      description: "Event generated by the app-events startup process",
      artist,
      venue,
      startsAt: startsAt.toISOString(),
      endsAt: endsAt.toISOString(),
      status: "confirmed",
    };

    const savedEvent = repository.createConfirmedEvent(event);
    logger.info(
      {
        eventId: savedEvent.id,
        eventName: savedEvent.name,
        capacity: savedEvent.venue.capacity,
        operation: "generateEvent",
      },
      "event generated",
    );
    return savedEvent;
  };

  return {
    start: () => {
      if (interval) {
        return;
      }

      generateEvent();
      interval = setInterval(generateEvent, intervalMs);
    },
    stop: () => {
      if (!interval) {
        return;
      }

      clearInterval(interval);
      interval = undefined;
    },
  };
}
